kotlin only ap working

diff --git a/kapt b/kapt
--- a/kapt
+++ b/kapt
@@ -24,8 +24,6 @@ info ( ) {
     echo "${bold}${blue} $* ${reset}"
 }
 
-set -xxx
-
 # Requires kotlin version 1.1.3+
 ensure kotlin 'https://kotlinlang.org/'
 
@@ -39,21 +37,21 @@ if [ -z "$KOTLIN_HOME" ]; then
   export KOTLIN_HOME=$(KOTLIN_RUNNER=1 JAVACMD=echo kotlinc | awk 'NR>1' RS=' ' | grep -F kotlin.home= | cut -d= -f2)
 fi
 
-# # Step 1: Creating ap jar
-# info "Creating annotation processing jar"
-# $KOTLIN_HOME/bin/kotlinc \
-# ./ap-kt/br/com/thales/buckt/ViewBinder.kt \
-# ./ap-kt/br/com/thales/buckt/VBProcessor.kt \
-# -classpath $CLASSPATH \
-# -d ap-kt/build/output \
-# -verbose \
-# -module-name my-kt-ap \
-# -no-stdlib \
-# -no-reflect \
-# && info "STEP 1 COMPLETE." || die "STEP 1 FAILED."
-#
-# # cp -r ap/resources/META-INF ap/build/output/META-INF
-# (cd ap-kt/build/output && zip -r my-ap-kt-lib META-INF br && mv my-ap-kt-lib.zip my-ap-kt-lib.jar && rm -rf META-INF && rm -rf br)
+# Step 1: Creating ap jar
+info "Creating annotation processing jar"
+$KOTLIN_HOME/bin/kotlinc \
+./ap-kt/br/com/thales/buckt/ViewBinder.kt \
+./ap-kt/br/com/thales/buckt/VBProcessor.kt \
+-classpath $CLASSPATH \
+-d ap-kt/build/output \
+-verbose \
+-module-name my-kt-ap \
+-no-stdlib \
+-no-reflect \
+&& info "STEP 1 COMPLETE." || die "STEP 1 FAILED."
+
+cp -r ap-kt/resources/META-INF ap-kt/build/output/META-INF
+(cd ap-kt/build/output && zip -r my-ap-kt-lib META-INF br && mv my-ap-kt-lib.zip my-ap-kt-lib.jar && rm -rf META-INF && rm -rf br)
 
 # Step 2: Creating ap jar
 info "Creating annotation processing jar"
@@ -68,65 +66,64 @@ javac \
 cp -r ap-java/resources/META-INF ap-java/build/output/META-INF
 (cd ap-java/build/output && zip -r my-ap-java-lib META-INF br && mv my-ap-java-lib.zip my-ap-java-lib.jar && rm -rf META-INF && rm -rf br)
 
-# # Step 1: Generate Stubs
-# info "Generating sample stubs"
-# $KOTLIN_HOME/bin/kotlinc \
-# sample/br/com/thales/buckt/AnnotatedMain.kt \
-# sample/br/com/thales/buckt/AnnotatedMainJava.java \
-# -Xadd-compiler-builtins \
-# -classpath $SAMPLE_CLASSPATH \
-# -d sample/build/output \
-# -verbose \
-# -Xload-builtins-from-dependencies \
-# -module-name my-ap-client \
-# -no-reflect \
-# -no-stdlib \
-# -Xplugin=$TOOLS_JAR \
-# -Xplugin=$ANNOTATION_PROCESSOR \
-# -P plugin:org.jetbrains.kotlin.kapt3:aptMode=stubs \
-# -P plugin:org.jetbrains.kotlin.kapt3:apclasspath=$WORKING_DIR/libs/kotlin-stdlib.jar \
-# -P plugin:org.jetbrains.kotlin.kapt3:apclasspath=$WORKING_DIR/ap/build/output/my-ap-lib.jar \
-# -P plugin:org.jetbrains.kotlin.kapt3:apclasspath=$WORKING_DIR/libs/com.squareup.kotlinpoet-0.5.0.jar \
-# -P plugin:org.jetbrains.kotlin.kapt3:sources=$SOURCES \
-# -P plugin:org.jetbrains.kotlin.kapt3:classes=$CLASSES \
-# -P plugin:org.jetbrains.kotlin.kapt3:incrementalData=$INCREMENTAL_DATA \
-# -P plugin:org.jetbrains.kotlin.kapt3:stubs=$STUBS \
-# -P plugin:org.jetbrains.kotlin.kapt3:apoptions=$GENERATED_DIR_MAP \
-# -P plugin:org.jetbrains.kotlin.kapt3:javacArguments=$EMPTY_MAP \
-# -P plugin:org.jetbrains.kotlin.kapt3:useLightAnalysis=$LIGHT_ANALYSIS \
-# -P plugin:org.jetbrains.kotlin.kapt3:correctErrorTypes=$CORRECT_ERROR_TYPES \
-# -P plugin:org.jetbrains.kotlin.kapt3:verbose=$VERBOSE \
-# && info "STEP 2 COMPLETE." || die "STEP 2 FAILED."
+# Step 1: Generate Stubs
+info "Generating sample stubs"
+$KOTLIN_HOME/bin/kotlinc \
+sample/br/com/thales/buckt/AnnotatedMain.kt \
+sample/br/com/thales/buckt/AnnotatedMainJava.java \
+-Xadd-compiler-builtins \
+-classpath $SAMPLE_CLASSPATH \
+-d sample/build/output \
+-verbose \
+-Xload-builtins-from-dependencies \
+-module-name my-ap-client \
+-no-reflect \
+-no-stdlib \
+-Xplugin=$TOOLS_JAR \
+-Xplugin=$ANNOTATION_PROCESSOR \
+-P plugin:org.jetbrains.kotlin.kapt3:aptMode=stubs \
+-P plugin:org.jetbrains.kotlin.kapt3:apclasspath=$WORKING_DIR/libs/kotlin-stdlib.jar \
+-P plugin:org.jetbrains.kotlin.kapt3:apclasspath=$WORKING_DIR/ap-kt/build/output/my-ap-kt-lib.jar \
+-P plugin:org.jetbrains.kotlin.kapt3:sources=$SOURCES \
+-P plugin:org.jetbrains.kotlin.kapt3:classes=$CLASSES \
+-P plugin:org.jetbrains.kotlin.kapt3:incrementalData=$INCREMENTAL_DATA \
+-P plugin:org.jetbrains.kotlin.kapt3:stubs=$STUBS \
+-P plugin:org.jetbrains.kotlin.kapt3:apoptions=$GENERATED_DIR_MAP \
+-P plugin:org.jetbrains.kotlin.kapt3:javacArguments=$EMPTY_MAP \
+-P plugin:org.jetbrains.kotlin.kapt3:useLightAnalysis=$LIGHT_ANALYSIS \
+-P plugin:org.jetbrains.kotlin.kapt3:correctErrorTypes=$CORRECT_ERROR_TYPES \
+-P plugin:org.jetbrains.kotlin.kapt3:verbose=$VERBOSE \
+&& info "STEP 3 COMPLETE." || die "STEP 3 FAILED."
 #
-# # Step 2: Run kapt
-# info "Running sample apt"
-# $KOTLIN_HOME/bin/kotlinc \
-# sample/br/com/thales/buckt/AnnotatedMain.kt \
-# sample/br/com/thales/buckt/AnnotatedMainJava.java \
-# -Xadd-compiler-builtins \
-# -classpath $SAMPLE_CLASSPATH \
-# -d sample/build/output \
-# -verbose \
-# -Xload-builtins-from-dependencies \
-# -module-name my-ap-client \
-# -no-reflect \
-# -no-stdlib \
-# -Xplugin=$TOOLS_JAR \
-# -Xplugin=$ANNOTATION_PROCESSOR \
-# -P plugin:org.jetbrains.kotlin.kapt3:aptMode=apt \
-# -P plugin:org.jetbrains.kotlin.kapt3:apclasspath=$WORKING_DIR/libs/kotlin-stdlib.jar \
-# -P plugin:org.jetbrains.kotlin.kapt3:apclasspath=$WORKING_DIR/ap/build/output/my-ap-lib.jar \
-# -P plugin:org.jetbrains.kotlin.kapt3:apclasspath=$WORKING_DIR/libs/com.squareup.kotlinpoet-0.5.0.jar \
-# -P plugin:org.jetbrains.kotlin.kapt3:sources=$SOURCES \
-# -P plugin:org.jetbrains.kotlin.kapt3:classes=$CLASSES \
-# -P plugin:org.jetbrains.kotlin.kapt3:incrementalData=$INCREMENTAL_DATA \
-# -P plugin:org.jetbrains.kotlin.kapt3:stubs=$STUBS \
-# -P plugin:org.jetbrains.kotlin.kapt3:apoptions=$GENERATED_DIR_MAP \
-# -P plugin:org.jetbrains.kotlin.kapt3:javacArguments=$EMPTY_MAP \
-# -P plugin:org.jetbrains.kotlin.kapt3:useLightAnalysis=$LIGHT_ANALYSIS \
-# -P plugin:org.jetbrains.kotlin.kapt3:correctErrorTypes=$CORRECT_ERROR_TYPES \
-# -P plugin:org.jetbrains.kotlin.kapt3:verbose=$VERBOSE \
-# && info "STEP 3 COMPLETE." || die "STEP 3 FAILED."
+# Step 2: Run kapt
+info "Running sample apt"
+$KOTLIN_HOME/bin/kotlinc \
+sample/br/com/thales/buckt/AnnotatedMain.kt \
+sample/br/com/thales/buckt/AnnotatedMainJava.java \
+-Xadd-compiler-builtins \
+-classpath $SAMPLE_CLASSPATH \
+-d sample/build/output \
+-verbose \
+-Xload-builtins-from-dependencies \
+-module-name my-ap-client \
+-no-reflect \
+-no-stdlib \
+-Xplugin=$TOOLS_JAR \
+-Xplugin=$ANNOTATION_PROCESSOR \
+-P plugin:org.jetbrains.kotlin.kapt3:aptMode=apt \
+-P plugin:org.jetbrains.kotlin.kapt3:apclasspath=$WORKING_DIR/libs/kotlin-stdlib.jar \
+-P plugin:org.jetbrains.kotlin.kapt3:apclasspath=$WORKING_DIR/libs/kotlin-reflect.jar \
+-P plugin:org.jetbrains.kotlin.kapt3:apclasspath=$WORKING_DIR/ap-kt/build/output/my-ap-kt-lib.jar \
+-P plugin:org.jetbrains.kotlin.kapt3:sources=$SOURCES \
+-P plugin:org.jetbrains.kotlin.kapt3:classes=$CLASSES \
+-P plugin:org.jetbrains.kotlin.kapt3:incrementalData=$INCREMENTAL_DATA \
+-P plugin:org.jetbrains.kotlin.kapt3:stubs=$STUBS \
+-P plugin:org.jetbrains.kotlin.kapt3:apoptions=$GENERATED_DIR_MAP \
+-P plugin:org.jetbrains.kotlin.kapt3:javacArguments=$EMPTY_MAP \
+-P plugin:org.jetbrains.kotlin.kapt3:useLightAnalysis=$LIGHT_ANALYSIS \
+-P plugin:org.jetbrains.kotlin.kapt3:correctErrorTypes=$CORRECT_ERROR_TYPES \
+-P plugin:org.jetbrains.kotlin.kapt3:verbose=$VERBOSE \
+&& info "STEP 4 COMPLETE." || die "STEP 4 FAILED."
 #
 # # Step 4: Invoke kotlinc normally
 # info "Compiling sample kotlin"
